### ISSUE TITLE
Small security issue

### ISSUE THREAD

**Issue by c-schmitz** [dimitrov84/limesurvey_sendadminnotifications#1]
The plugin looks fine. Small issue might be in line 60 - you should sanitize to an integer here since the request is user input and to avoid string injection.

**Comment by dimitrov84** [comment]
Thank you for the report.
I've added some code to validate and sanitize the data coming in from requests. There were some additional places in the newDirectRequest that needed a quick tweak as well.

**Comment by c-schmitz** [comment]
👍 Looks fine, now!
